language: php

branches:
  only:
    - master
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

sudo: false

install:
  - rm composer.lock
  - composer install

script:
  - php ./vendor/bin/phpunit
